// 100 هاشتاق أولي للوظائف والحراج

const initialHashtags = [
  // === حراج - سيارات (15) ===
  { tag: "سيارات", category: "haraj" },
  { tag: "سيارات_مستعملة", category: "haraj" },
  { tag: "سيارات_للبيع", category: "haraj" },
  { tag: "سيارات_جديدة", category: "haraj" },
  { tag: "سيارات_نظيفة", category: "haraj" },
  { tag: "تويوتا", category: "haraj" },
  { tag: "هونداي", category: "haraj" },
  { tag: "نيسان", category: "haraj" },
  { tag: "فورد", category: "haraj" },
  { tag: "شفروليه", category: "haraj" },
  { tag: "مرسيدس", category: "haraj" },
  { tag: "بي_ام_دبليو", category: "haraj" },
  { tag: "لكزس", category: "haraj" },
  { tag: "جيب", category: "haraj" },
  { tag: "دباب", category: "haraj" },

  // === حراج - عقارات (15) ===
  { tag: "عقارات", category: "haraj" },
  { tag: "عقارات_للبيع", category: "haraj" },
  { tag: "عقارات_للإيجار", category: "haraj" },
  { tag: "شقق", category: "haraj" },
  { tag: "شقق_للإيجار", category: "haraj" },
  { tag: "فلل", category: "haraj" },
  { tag: "فلل_للبيع", category: "haraj" },
  { tag: "أراضي", category: "haraj" },
  { tag: "أراضي_للبيع", category: "haraj" },
  { tag: "محلات", category: "haraj" },
  { tag: "مكاتب", category: "haraj" },
  { tag: "مستودعات", category: "haraj" },
  { tag: "استراحات", category: "haraj" },
  { tag: "مزارع", category: "haraj" },
  { tag: "عمارات", category: "haraj" },

  // === حراج - إلكترونيات (10) ===
  { tag: "جوالات", category: "haraj" },
  { tag: "ايفون", category: "haraj" },
  { tag: "سامسونج", category: "haraj" },
  { tag: "لابتوب", category: "haraj" },
  { tag: "كمبيوتر", category: "haraj" },
  { tag: "تابلت", category: "haraj" },
  { tag: "ساعات_ذكية", category: "haraj" },
  { tag: "سماعات", category: "haraj" },
  { tag: "كاميرات", category: "haraj" },
  { tag: "بلايستيشن", category: "haraj" },

  // === حراج - أثاث ومنزلية (10) ===
  { tag: "أثاث", category: "haraj" },
  { tag: "مكيفات", category: "haraj" },
  { tag: "ثلاجات", category: "haraj" },
  { tag: "غسالات", category: "haraj" },
  { tag: "مطابخ", category: "haraj" },
  { tag: "كنب", category: "haraj" },
  { tag: "طاولات", category: "haraj" },
  { tag: "سجاد", category: "haraj" },
  { tag: "ستائر", category: "haraj" },
  { tag: "ديكورات", category: "haraj" },

  // === وظائف - عامة (15) ===
  { tag: "وظائف", category: "jobs" },
  { tag: "وظائف_شاغرة", category: "jobs" },
  { tag: "وظائف_الرياض", category: "jobs" },
  { tag: "وظائف_جدة", category: "jobs" },
  { tag: "وظائف_الدمام", category: "jobs" },
  { tag: "توظيف", category: "jobs" },
  { tag: "توظيف_فوري", category: "jobs" },
  { tag: "مطلوب_موظفين", category: "jobs" },
  { tag: "فرص_عمل", category: "jobs" },
  { tag: "عمل", category: "jobs" },
  { tag: "دوام_كامل", category: "jobs" },
  { tag: "دوام_جزئي", category: "jobs" },
  { tag: "عن_بعد", category: "jobs" },
  { tag: "فريلانس", category: "jobs" },
  { tag: "تدريب", category: "jobs" },

  // === وظائف - مهن (20) ===
  { tag: "سائق", category: "jobs" },
  { tag: "سائق_خاص", category: "jobs" },
  { tag: "سائق_عام", category: "jobs" },
  { tag: "كهربائي", category: "jobs" },
  { tag: "سباك", category: "jobs" },
  { tag: "نجار", category: "jobs" },
  { tag: "حداد", category: "jobs" },
  { tag: "دهان", category: "jobs" },
  { tag: "عامل_بناء", category: "jobs" },
  { tag: "طباخ", category: "jobs" },
  { tag: "مزارع", category: "jobs" },
  { tag: "حارس", category: "jobs" },
  { tag: "حارس_أمن", category: "jobs" },
  { tag: "عامل_نظافة", category: "jobs" },
  { tag: "مربية", category: "jobs" },
  { tag: "خادمة", category: "jobs" },
  { tag: "مدرس", category: "jobs" },
  { tag: "معلم", category: "jobs" },
  { tag: "مصمم", category: "jobs" },
  { tag: "مبرمج", category: "jobs" },

  // === مواقع (15) ===
  { tag: "الرياض", category: "location" },
  { tag: "جدة", category: "location" },
  { tag: "الدمام", category: "location" },
  { tag: "مكة", category: "location" },
  { tag: "المدينة", category: "location" },
  { tag: "الطائف", category: "location" },
  { tag: "أبها", category: "location" },
  { tag: "تبوك", category: "location" },
  { tag: "القصيم", category: "location" },
  { tag: "حائل", category: "location" },
  { tag: "جازان", category: "location" },
  { tag: "نجران", category: "location" },
  { tag: "الباحة", category: "location" },
  { tag: "الجوف", category: "location" },
  { tag: "عرعر", category: "location" },
];

module.exports = initialHashtags;
